import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sandwormSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Intro",
    },
    {
      type: "doc",
      id: "quick-start/index",
      label: "Quick Start",
    },
    {
      type: "category",
      label: "WQL Syntax",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "sql-syntax",
        },
      ],
    },
    {
      type: "category",
      label: "Webapp",
      collapsible: true,
      collapsed: false,
      items: [
        "web-app/index",
        "web-app/explore",
        {
          type: "autogenerated",
          dirName: "web-app/workspace",
        },
      ],
    },
    {
      type: "doc",
      id: "contributing",
      label: "Contributing",
    },
    {
      type: "doc",
      id: "faq",
      label: "FAQ & Troubleshooting",
    },
  ],
};

export default sidebars;
